server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: WARN
  # Logger-specific levels.pay
  loggers:
    deprecation: ERROR
    ExecutionGraphGenerator: WARN
    org.hibernate: ERROR
    QueuedSender: WARN
    feign: DEBUG

  appenders:
    - type: console
      threshold: DEBUG
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

rabbit:
  brokers:
    - host: localhost
      port: 5672
  exchange: callback_messages
  threadPoolSize: 300
  userName: guest
  password: guest

actorRmqConfig:
  brokers:
    - host: localhost
      port: 5672
  userName: guest
  threadPoolSize: 300
  password: guest

serviceDiscovery:
  namespace: phonepe
  environment: local
  zookeeper: localhost:2181
  publishedHost: 127.0.0.1
  publishedPort: 8080

riemann:
  host: riemann-stage.phonepe.int
  port: 5555
  prefix: phonepe.local.callback
  pollingInterval: 30
  tags:
    - foxtrot

callbackQueueConfig:
  configList:
    - queue: test

actors:
  CALLBACK:
    exchange: callback_messages
    delayed: false
    prefix: callback.actors
    concurrency: 3
    prefetchCount: 1
    retryConfig:
      type: COUNT_LIMITED_EXPONENTIAL_BACKOFF
      maxAttempts: 6
      multipier: 50
      maxTimeBetweenRetries: 30s

revolver:
  hystrixStreamPath: /hystrix.stream
  mailBox:
    type: in_memory
  clientConfig:
    clientName: phonepe-api
  serviceResolverConfig:
    useCurator: false
    zkConnectionString: "prd-appzk001.phonepe.nm1:2181,prd-appzk002.phonepe.nm1:2181,prd-appzk003.phonepe.nm1:2181"
    namespace: phonepe
  services:
    - type: http
      service: foxtrot
      connectionPoolSize: 5
      connectionKeepAliveInMillis: 60000
      authEnabled: false
      endpoint:
        type: simple
        host: localhost
        port: 17000
      apis:
        - api: cw_schedule
          path: "foxtrot/v1/tables"
          methods:
            - GET
          authorization:
            type: static
            methods:
              - GET
            roles:
              - internal-service
          runtime:
            threadPool:
              concurrency: 2
              timeout: 2000