server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

checkmate:
  requestValidation: false
  responseChecksum: false
  clockSkew: 120
  algorithm: AES/ECB/PKCS5Padding
  whiteList:
    - revolver/v1/callback/{requestId}
    - revolver/dashboard
    - revolver/v1/metadata/status
    - revolver/v1/metadata/config
    - revolver/v1/request/status/{requestId}
    - revolver/v1/request/ack/{requestId}
    - revolver/v1/response/{requestId}
    - apis/callback/foxtrot/foxtrot/v1/tables

logging:
  level: WARN
  # Logger-specific levels.pay
  loggers:
    deprecation: ERROR
    ExecutionGraphGenerator: WARN
    org.hibernate: ERROR
    QueuedSender: WARN
    feign: DEBUG

  appenders:
    - type: console
      threshold: DEBUG
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

rmqConfig:
  brokers:
    - host: localhost
      port: 5672
  threadPoolSize: 2
  userName: guest
  password: guest

discovery:
  namespace: phonepe
  environment: local
  zookeeper: localhost:2181
  publishedHost: 127.0.0.1
  publishedPort: 8080

riemann:
  host: riemann-stage.local.int
  port: 5555
  prefix: local.callback
  pollingInterval: 30
  tags:
    - foxtrot

actors:
  DEFAULT:
    exchange: callback_messages
    delayed: false
    prefix: callback.actors
    concurrency: 3
    prefetchCount: 1
    retryConfig:
      type: COUNT_LIMITED_EXPONENTIAL_BACKOFF
      maxAttempts: 6
      multipier: 50
      maxTimeBetweenRetries: 30s
  foxtrot-queue:
    exchange: callback_messages
    delayed: false
    prefix: callback.actors
    concurrency: 3
    prefetchCount: 1
    retryConfig:
      type: COUNT_LIMITED_EXPONENTIAL_BACKOFF
      maxAttempts: 6
      multipier: 50
      maxTimeBetweenRetries: 30s

primer:
  enabled: false
  endpoint:
    type: ranger
    namespace: phonepe
    service: primer
    environment: local
    zookeeper: localhost:2181
  cacheExpiry: 10
  cacheMaxSize: 100000
  clockSkew: 60
  prefix: Bearer
  privateKey: TwhjV5ujkvb41frpmqCve7ZfhqwSDMqOXe01DeDIsb2xCrW4bwfFnax9bi2uC9Kn
  whileListUrl:
    - revolver/v1/callback/{requestId}
    - revolver/dashboard
    - revolver/v1/metadata/status
    - revolver/v1/metadata/config
    - revolver/v1/request/status/{requestId}
    - revolver/v1/request/ack/{requestId}
    - revolver/v1/response/{requestId}
    - apis/users/foxtrot/v1/tables

revolver:
  hystrixStreamPath: /hystrix.stream
  mailBox:
    type: in_memory
  clientConfig:
    clientName: local-api
  serviceResolverConfig:
    useCurator: false
    zkConnectionString: "localhost:2181"
    namespace: local
  callbackTimeout: 3000
  services:
    - type: http
      service: foxtrot
      connectionPoolSize: 5
      connectionKeepAliveInMillis: 60000
      authEnabled: false
      endpoint:
        type: simple
        host: localhost
        port: 17000
      apis:
        - api: cw_schedule
          path: "foxtrot/v1/tables"
          methods:
            - GET
          authorization:
            type: static
            methods:
              - GET
            roles:
              - internal-service
          whitelist: true
          runtime:
            threadPool:
              concurrency: 2
              timeout: 20000
          callbackQueueId: foxtrot-queue